module.exports = {
  author: require('./author'),
  bin: require('./bin'),
  bugs: require('./bugs'),
  contributors: require('./contributors'),
  collaborators: require('./collaborators'),
  description: require('./description'),
  dependencies: require('./dependencies'),
  devDependencies: require('./devDependencies'),
  engines: require('./engines'),
  files: require('./files'),
  homepage: require('./homepage'),
  keywords: require('./keywords'),
  license: require('./license'),
  main: require('./main'),
  maintainers: require('./maintainers'),
  name: require('./name'),
  preferGlobal: require('./preferGlobal'),
  private: require('./private'),
  repository: require('./repository'),
  scripts: require('./scripts'),
  types: require('./types'),
  typings: require('./typings'),
  version: require('./version')
};

